name: Build plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: logseq-done-time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r logseq-worked-on.zip dist README.md package.json LICENSE icon.png
      - uses: softprops/action-gh-release@v2
        with:
          files: |
            package.json
            *.zip
