name: Build plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: logseq-done-time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - uses: mskelton/setup-yarn@v1
      - run: yarn
      - run: yarn build
      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r logseq-done-time.zip dist README.md package.json LICENSE icon.png
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            package.json
            *.zip
